name: Backend CI

on:
    push:
        paths:
            - 'Back-End/**'
    pull_request:
        paths:
            - 'Back-End/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
            
            - name: Build with Maven
              run: |
                cd Back-End
                ./mvnw clean install

            - name: Run tests
              run: |
                cd Back-End
                .mvnw test